env: development

server:
  listen_ipv4: 127.0.0.1    # leave blank to disable ipv4
  listen_ipv6: ::1          # leave blank to disable ipv6
  tls_cert_path:            # leave blank to not use https
  tls_key_path:             # leave blank to not use https
  port: 3000
  base_path: /

app:
  aggregation_time: '02:15' # time at which to run daily aggregation batch jobs
  counting_time: '05:15'    # time at which to run daily job to count total hours tracked in the system
  custom_languages:
    vue: Vue
    jsx: JSX

db:
  host:                     # leave blank when using sqlite3
  port:                     # leave blank when using sqlite3
  user:                     # leave blank when using sqlite3
  password:                 # leave blank when using sqlite3
  name: wakapi_db.db        # database name for mysql / postgres or file path for sqlite (e.g. /tmp/wakapi.db)
  dialect: sqlite3          # mysql, postgres, sqlite3
  max_conn: 2               # maximum number of concurrent connections to maintain
  ssl: false                # whether to use tls for db connection (must be true for cockroachdb) (ignored for mysql and sqlite)

security:
  password_salt:            # CHANGE !
  insecure_cookies: false
  cookie_max_age: 172800
  allow_signup: true